In [1]:
import jax
import jax.numpy as jnp
import immrax as irx


In [3]:
def f (t, x) :
    # print(args)
    # x = args[1]
    # t, x = args
    return jnp.array([-x[1], x[0]])

it0 = irx.icentpert([0.], [0.1])
ix0 = irx.icentpert(jnp.ones(2), 0.1)
tmt0 = irx.taylor_model_identity(it0, order=4)
tmx0 = irx.taylor_model_identity(ix0, order=2)
tm_t0x0 = irx.taylor_model_identity((it0, ix0), order=[4, 2])
print(tm_t0x0.exponents)
print(tm_t0x0.domain_treedef)
print(tm_t0x0.is_structured)
print(tm_t0x0.structured_center)

print(irx.nattm(f, structured_center=True)(tm_t0x0))
# print(irx.nattm(f, structured_center=False)([tmt0, tmx0]))

# f_tm = irx.nattm(f)
# print(f_tm(tm0))

# integ_tm0 = irx.integrate_variable(tm0, 0)
# print(integ_tm0.coeffs, integ_tm0.exponents)

# def K (tm) :
#     # Picard Operator
#     # Integrate tm from t_0 to t

#     tm_intt = irx.integrate_variable(tm, )



[[0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4]
 [0 0 0 1 1 2 0 0 0 1 1 2 0 0 0 1 1 2 0 0 0 1 1 2 0 0 0 1 1 2]
 [0 1 2 0 1 0 0 1 2 0 1 0 0 1 2 0 1 0 0 1 2 0 1 0 0 1 2 0 1 0]]
PyTreeDef((*, *))
True
(Array([0.], dtype=float32), Array([1., 1.], dtype=float32))
TaylorModel(shape=(2,), d=3, order=(4, 2, 2), monomials=30)
